"""Initial migration

Revision ID: eea852c04325
Revises: 
Create Date: 2026-07-12 17:35:41.610354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea852c04325'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('parent_number', sa.String(length=10), nullable=True),
    sa.Column('acct_class', sa.SmallInteger(), nullable=False),
    sa.Column('balance_nature', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['parent_number'], ['account.number'], ),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_app_user_id'), 'app_user', ['id'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('tax_code', sa.String(length=14), nullable=True),
    sa.Column('student_name', sa.String(length=255), nullable=True),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('tax_code', sa.String(length=14), nullable=True),
    sa.Column('goods_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_id'), 'partner', ['id'], unique=False)
    op.create_table('opening_balance',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=10), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['account_number'], ['account.number'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'account_number', 'partner_id')
    )
    op.create_table('voucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('voucher_no', sa.String(length=20), nullable=False),
    sa.Column('voucher_type', sa.String(length=10), nullable=False),
    sa.Column('cash_source', sa.String(length=3), nullable=False),
    sa.Column('txn_kind', sa.String(length=20), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('attached_docs', sa.SmallInteger(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_id'), 'voucher', ['id'], unique=False)
    op.create_table('ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('narration', sa.String(length=500), nullable=True),
    sa.Column('debit_acct', sa.String(length=10), nullable=False),
    sa.Column('credit_acct', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['credit_acct'], ['account.number'], ),
    sa.ForeignKeyConstraint(['debit_acct'], ['account.number'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['voucher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entry_id'), 'ledger_entry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entry_id'), table_name='ledger_entry')
    op.drop_table('ledger_entry')
    op.drop_index(op.f('ix_voucher_id'), table_name='voucher')
    op.drop_table('voucher')
    op.drop_table('opening_balance')
    op.drop_index(op.f('ix_partner_id'), table_name='partner')
    op.drop_table('partner')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_app_user_id'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('account')
    # ### end Alembic commands ###
